### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by zqlq4ever** [Mr-lin930819/ComposeMany#2]
![3d61d788d734f785c80b0fb76db185c](https://user-images.githubusercontent.com/37474811/139016490-66317840-2da0-4d21-9cab-4f68b7cf2777.jpg)

**Comment by Mr-lin930819** [comment]
@zqlq4ever 修改了账号id为long类型，可尝试是否已修复。提交记录：https://github.com/Mr-lin930819/ComposeMany/commit/ac8826278a8ad077cd26928289ee12e3068e5fbc

**Comment by zqlq4ever** [comment]
@Mr-lin930819 这次变成了 account.createTime 。错误一样。

**Comment by Mr-lin930819** [comment]
> @Mr-lin930819 这次变成了 account.createTime 。错误一样。

@zqlq4ever 做了同样的修复了。估计是因为你的账号比较晚注册，所以这些数据比较大。我自己账号比较早的，所以没发现这些问题😂
